[project]
name = "apposax"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "lucabesnard", email = "luca.besnard@etudiant.univ-rennes.fr" }
]
requires-python = ">=3.9"
dependencies = [
    "dash>=4.4.1",
    "gunicorn>=23.0.0",
    "matplotlib>=3.9.4",
]

[project.scripts]
apposax = "apposax:main"

[build-system]
requires = ["uv_build>=0.12.14,<0.13.0"]
build-backend = "uv_build"
